name: Install Laravel

on:
  workflow_call:
    inputs:
      php-version:
        type: string
        description: "The PHP version to run this workflow on"
        required: true
      laravel-version:
        type: string
        description: "The Laravel version to run this workflow on"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer, phpunit
          coverage: none

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ inputs.laravel-version }}" --no-update
          composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Set SQLite File Permissions
        run: chmod 777 database/database.sqlite

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run package tests
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ./database/database.sqlite
        run: |
          php artisan migrate --force
          php artisan test --env=testing
