name: Install Laravel

on:
  workflow_call:
    inputs:
      php-version:
        type: string
        description: "The PHP version to run this workflow on"
        required: true
      laravel-version:
        type: string
        description: "The Laravel version to run this workflow on"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer, phpunit
          coverage: none

      - name: "Install Laravel Project: ${{ inputs.laravel-version }}"
        run: composer create-project --prefer-dist laravel/laravel laravel-${{ inputs.laravel-version }} "${{ inputs.laravel-version }}"

      - name: App directory
        run: |
          cd laravel-${{ inputs.laravel-version }}
          ls -la

      - name: Set SQLite File Permissions
        run: |
          cd laravel-${{ inputs.laravel-version }}
          touch database/database.sqlite
          chmod 777 database/database.sqlite

      - name: Directory Permissions
        run: |
          cd laravel-${{ inputs.laravel-version }}
          chmod -R 777 storage bootstrap/cache

      - name: Generate Application Key
        run: |
          cd laravel-${{ inputs.laravel-version }}
          php artisan key:generate

      - name: Serve Laravel Application
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ./database/database.sqlite
        run: |
          cd laravel-${{ inputs.laravel-version }}
          php artisan migrate --force
          php artisan serve --host=0.0.0.0 --port=8000 &

      - name: Wait for Server to Start
        run: |
          sleep 10  # Adjust the sleep time as needed to ensure the server is ready

      - name: Run Package Tests
        run: |
          cd laravel-${{ inputs.laravel-version }}
          php artisan test --env=testing

