name: Install Laravel

on:
  workflow_call:
    inputs:
      php-version:
        type: string
        description: "The PHP version to run this workflow on"
        required: true
      laravel-version:
        type: string
        description: "The Laravel version to run this workflow on"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer, phpunit
          coverage: none

      - name: "Install Laravel Project: ${{ inputs.laravel-version }}"
        run: composer create-project --prefer-dist laravel/laravel laravel-${{ inputs.laravel-version }} "${{ inputs.laravel-version }}"

      - name: App directory
        working-directory: laravel-${{ inputs.laravel-version }}
        run: ls -la

      - name: Set SQLite File Permissions
        working-directory: laravel-${{ inputs.laravel-version }}
        run: |
          touch database/database.sqlite
          chmod 777 database/database.sqlite

      - name: Directory Permissions
        working-directory: laravel-${{ inputs.laravel-version }}
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate Application Key
        working-directory: laravel-${{ inputs.laravel-version }}
        run: php artisan key:generate

      - name: Install LaraPanel Package
        working-directory: laravel-${{ inputs.laravel-version }}
        run: composer require weprodev/larapanel

      - name: Serve Laravel Application
        working-directory: laravel-${{ inputs.laravel-version }}
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ./database/database.sqlite
        run: |
          php artisan migrate --force
          php artisan db:seed

