name: Test LaraPanel Pkg

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  install-laravel:
    strategy:
      matrix:
        php-version: [8.2, 8.3]
        laravel-version: ["10.*", "11.*"]
    uses: weprodev/LaraPanel/.github/workflows/install-laravel.yml@master
    with:
      php-version: ${{ matrix.php-version }}
      laravel-version: ${{ matrix.laravel-version }}
