name: Test LaraPanel Pkg for new changes

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get codes
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer, phpunit
          coverage: none

      - name: Install LaraPanel Framework
        run: composer create-project weprodev/larapanel-framework

      - name: Delete all existing migration files
        working-directory: larapanel-framework
        run: |
          for pattern in "database/migrations/2024_*create_users_table.php" \
                         "database/migrations/2024_*create_groups_table.php" \
                         "database/migrations/2024_*edit_permission_tables.php"; do
            matches=$(ls $pattern 2>/dev/null | wc -l)
            if [ $matches -gt 1 ]; then
              echo "Duplicate migration files found for pattern: $pattern. Keeping only the first."
              ls $pattern | tail -n +2 | xargs rm -f
            fi
          done

      - name: Link Local Package
        working-directory: larapanel-framework
        run: |
          composer config repositories.local '{"type": "path", "minimum-stability": "dev", "url": "../", "options": {"symlink": true}}'
          composer clear-cache
          composer require weprodev/larapanel:@dev --no-cache --no-update

      - name: Debug Composer Dependencies
        working-directory: larapanel-framework
        run: composer show weprodev/larapanel

      - name: Set SQLite File Permissions
        working-directory: larapanel-framework
        run: |
          touch database/database.sqlite
          chmod 777 database/database.sqlite

      - name: Directory Permissions
        working-directory: larapanel-framework
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate Application Key
        working-directory: larapanel-framework
        run: php artisan key:generate

      - name: Vendor publish provider
        working-directory: larapanel-framework
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ./database/database.sqlite
        run: |
          echo "Publishing Shared Service file"
          php artisan vendor:publish --provider=WeProDev\LaraPanel\Infrastructure\Shared\Provider\SharedServiceProvider --force

          echo "Publishing Panel Provider files"
          php artisan vendor:publish --provider=WeProDev\LaraPanel\Infrastructure\Panel\Provider\PanelServiceProvider --force

          echo "Publishing User module files"
          php artisan vendor:publish --provider=WeProDev\LaraPanel\Infrastructure\User\Provider\UserServiceProvider --force

      - name: Executing migration and seeder files
        working-directory: larapanel-framework
        run: |
          php artisan migrate:fresh --force
          php artisan db:seed --force

      - name: Execute E2E testing
        working-directory: larapanel-framework
        run: php artisan test
