name: Test LaraPanel Pkg

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3]
        laravel-version: ["10.*", "11.*"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Call the reusable workflow for Laravel installation
      - name: Installing Laravel
        uses: weprodev/LaraPanel/.github/workflows/install-laravel.yml@master
        with:
          php-version: ${{ matrix.php-version }}
          laravel-version: ${{ matrix.laravel-version }}

      # Install your package after Laravel is installed
      - name: Install LaraPanel Package
        run: |
          composer require weprodev/larapanel

      # Run E2E Tests (example placeholder)
      - name: Run E2E Tests
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ./database/database.sqlite
        run: |
          # Add your E2E test framework setup and commands here
          php artisan test
