name: Test LaraPanel Pkg

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-laravel:
    strategy:
      matrix:
        php-version: [8.2, 8.3]
        laravel-version: ["10.*", "11.*"]
    uses: weprodev/LaraPanel/.github/workflows/install-laravel.yml@master
    with:
      php-version: ${{ matrix.php-version }}
      laravel-version: ${{ matrix.laravel-version }}

  test-execution:
    needs: install-laravel

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LaraPanel Package
        run: composer require weprodev/larapanel

      - name: Run E2E Tests
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ./database/database.sqlite
        run: |
          php artisan migrate --force
          php artisan test
